server:
  port: 8888

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tail-s/Spring-Cloud-Config.git
          default-label: master
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh